import Navbar from "./components/Navbar";
import { CartProvider } from "./context/CartContext";

import { Box } from "@mui/material";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar />
          <Box component="main" minHeight={`calc(100dvh - 355px)`}>
            {children}
          </Box>
        </CartProvider>
      </body>
    </html>
  );
}
